import Head from "next/head";
import Image from "next/image";
import Animation from "../components/Blocks/Animation";
import Hero from "../components/Hero";
import PictureAndTextBlock from "../components/Blocks/PictureAndTextBlock";
import { useTheme } from "../context/ThemeContext";
import style from "../styles/Page.module.css";
import StandardContentBlock from "../components/Blocks/StandardContentBlock";
import TextTextBlock from "../components/Blocks/TextTextBlock";

export default function Home() {
  const { darkMode } = useTheme();
  
  return (
    <div
      className={
        darkMode ? `${style.container} ${style.darkmode}` : style.container
      }
    >
      <Head>
        <title>Affiliate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="index, follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <StandardContentBlock
        headingElement={"h2"}
        headingText={"Vad är ett omstartslån?"}
        contentText={`
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum ipsam
          esse velit ducimus autem id repellat, neque, eaque vitae inventore
          fugiat quod, placeat cumque fugit? Sit iusto commodi possimus sed.
          Nihil, consectetur aliquid minima aliquam commodi ipsum recusandae,
          autem quam fugit, quidem nam quod tenetur sequi quos quas atque animi
          at. Architecto facere maxime reprehenderit nesciunt repudiandae
          laudantium eligendi quam? Maiores fugit laudantium quam odio, minima
          quasi asperiores ratione at atque itaque dolorem vitae distinctio
          repellendus voluptatem quidem ipsam sint dolores non labore fuga
          placeat, mollitia explicabo assumenda! At, obcaecati! Fugit cum,
          incidunt voluptas eius aliquam unde, asperiores soluta ex repellendus
          nisi quidem, expedita modi hic porro consequatur facilis ratione animi
          exercitationem architecto at sint sequi delectus. Unde, aliquam
          laboriosam.
          `}
      />

      <Animation animationType={"slideFromRight"} boxHeight={300} duration={1}>
        <StandardContentBlock
          headingElement="h2"
          headingText="Var kan man få ett omstartslån?"
          contentText="
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum ipsam
            esse velit ducimus autem id repellat, neque, eaque vitae inventore
            fugiat quod, placeat cumque fugit? Sit iusto commodi possimus sed.
            Nihil, consectetur aliquid minima aliquam commodi ipsum recusandae,
            autem quam fugit, quidem nam quod tenetur sequi quos quas atque
            animi at. Architecto facere maxime reprehenderit nesciunt
            repudiandae laudantium eligendi quam? Maiores fugit laudantium quam
            odio, minima quasi asperiores ratione at atque itaque dolorem vitae
            distinctio repellendus voluptatem quidem ipsam sint dolores non
            labore fuga placeat, mollitia explicabo assumenda! At, obcaecati!
            Fugit cum, incidunt voluptas eius aliquam unde, asperiores soluta ex
            repellendus nisi quidem, expedita modi hic porro consequatur facilis
            ratione animi exercitationem architecto at sint sequi delectus.
            Unde, aliquam laboriosam."
        />
      </Animation>


           

      <TextTextBlock
        animate={true}
        firstHeadingElement="h3"
        firstHeading="Omstartslån utan säkerhet"
        firstContentText="Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque
              similique autem dolor obcaecati excepturi placeat totam fugiat!
              Consequatur, non laboriosam magnam, ducimus repellat natus
              officiis eos totam vitae libero ad. Accusantium eum at suscipit
              dolor, neque labore nesciunt amet sunt, sequi obcaecati dolores
              architecto quis vitae illo modi. Repellat pariatur non sint!"
        secondHeadingElement="h3"
        secondHeading="Omstartslån utan medsökande"
        secondContentText="Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius
      ratione alias, esse, et quae magni consequatur delectus tempore
      expedita iusto neque temporibus optio debitis at repellat
      cupiditate libero rem accusamus? Lorem ipsum dolor sit amet
      consectetur adipisicing elit. Accusantium eum at suscipit dolor,
      neque labore nesciunt amet sunt, sequi obcaecati dolores
      architecto quis vitae illo modi. Repellat pariatur non sint!"
      />


      <PictureAndTextBlock
        height={300}
        pictureNode={2}
        flipImage={true}
        background={"whitesmoke"}
        padding={20}
        imgUrl={"https://images.unsplash.com/photo-1670396118274-4f14fdd6323d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"}
        >
        <div>
          <StandardContentBlock headingElement="h3" headingText="Omstartslån med anmärkning" contentText="ratione alias, esse, et quae magni consequatur delectus tempore
          expedita iusto neque temporibus optio debitis at repellat
          cupiditate libero rem accusamus? Lorem ipsum dolor sit amet
          consectetur adipisicing elit. Accusantium eum at suscipit dolor,
          neque labore nesciunt amet sunt, sequi obcaecati dolores
          architecto quis vitae illo modi. Repellat pariatur non sint!"/>
        </div>
      </PictureAndTextBlock> 

      <Animation animationType={"fadeIn"} duration={2} delay={300} boxHeight={100}>
        <section className={style.twoCards}>
          <div className={style.card}>
            <h3>Tips om omstartslån</h3>
          </div>
          <div className={style.card}>
            <h3>Mer om omstartslån</h3>
          </div>
        </section>
      </Animation>
      
    </div>
  );
}
